project: 
  type: website
  output-dir: docs

website:
  title: "Nicholas Stevenson - Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Tidy Tuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/yosoynoob/NicholasStevenson-P2-Portfolio      

format:
  html:
    theme: superhero
    highlight: zenburn
    css: styles.css
    background-color: red;
    toc: FALSE


